### ISSUE TITLE
Customizable filter override for parsing lines

### ISSUE THREAD

**Issue by marcosrmendezaw** [jhuckaby/pixl-json-stream#1]
Hi,

Can we add an override to decide when to process a line? For example instead of just:

if (record.match(/\S/)) { ... }

we could do something like: 

if (self._processRecord(record)) { ... }

**Comment by jhuckaby** [comment]
The `record.match(/\S/)` simply filters out blank lines, which could theoretically happen if the stream has a leading or trailing EOL or something.  Not sure what value `_processRecord()` would add here.  Can you explain would it do other than what the default code already does?

I'm not against adding it, I'm just concerned about inserting a function call to low-level code which can potentially get called tens of thousands of times per second.

**Comment by marcosrmendezaw** [comment]
Hi Joseph,

Thank you for responding. The main thing that we'd like to do is exclude
things that are not json. So we could in addition to the record.match that
you have there or instead of it, add some expression that checks that the
line is not empty and that it starts and ends with a brace. Things like
that. We're specifically worried about performance and that's why we want
to exclude things that would waste a JSON.parse and throw an exception,
which trigger an event.

Regards,
Marcos

**Comment by jhuckaby** [comment]
Hey Marcos,

Thanks for the explanation.  I see and understand your point now.  I would be happy to add this functionality, but let me propose something slightly different.  I am still worried about adding a function call in such a time-critical piece of the code, because that adds overhead.  Would it be acceptable if we made the regular expression itself a member variable, which you could then simply override in your subclass?  So something like this in the base class definition:

``` javascript
{
    recordRegExp: /\S/
}
```

Then the code would change to:

``` javascript
if (record.match(this.recordRegExp)) {
```

So then you could just override the `recordRegExp` member variable with whatever regular expression you wanted.

Would this satisfy your needs?

**Comment by marcosrmendezaw** [comment]
sounds good to me. :D

**Comment by jhuckaby** [comment]
'Tis done :)
